article/urls.py
from django.urls import path
from article.views import HomepageView, ArticleListView, ArticleDetailView, UserRegisterView, ArticleCreateView


app_name = "article"

urlpatterns = [
 path('', HomepageView.as_view(), name="home"),
 path('all-articles/', ArticleListView.as_view(), name="all_articles"),
 path('article/<int:pk>/', ArticleDetailView.as_view(), name="article_detail"),
 path('accounts/register', UserRegisterView.as_view(), name="register"),
 path('create-article/', ArticleCreateView.as_view(), name="article_create")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Article(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()
    synopsis = models.TextField(max_length=500, null=True, blank=True)
    content = models.TextField()
    image_url = models.URLField(null=True, blank=True)
    categories = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', kwargs={'pk': self.pk})

article/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm, User
from django.contrib.auth.mixins import LoginRequiredMixin
from article.models import Article


class HomepageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_articles'] = Article.objects.all().order_by('-pk')
        context['latest_articles'] = Article.objects.all()[:5]
        context['last_article'] = Article.objects.last()
        return context


class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_detail.html'


class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')


class UserLoginView(LoginView):
    model = User
    template_name = 'registration/login.html'
    success_url = reverse_lazy('article:home')


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = '__all__'
    template_name = 'article_form.html'

templates/article_detail.html
{% extends 'base.html' %}

{% load markdown_extras %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
    <div class="w-50 mx-auto py-5 d-flex flex-column align-items-center gap-5">
        <h1>{{ article.title }}</h1>
        <img src="{{ article.image_url }}" alt="{{ article.categories }}" class="w-100 rounded shadow">
        <div>
            <p>{{ article.content | markdown | safe }}</p>
        </div>
    </div>
{% endblock %}

templates/article_form.html
{% extends 'base.html' %}

{% block title %} Create Article {% endblock %}

{% block content %}
    <div style="min-height: 80vh; padding: 2rem; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 3rem;">
        <h1>Create an article</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div style="width: 500px; padding: 2rem;" class="mb-5 border border-1 border-dark-subtle rounded-2 shadow">
                {% for field in form %}
                    <p style="display: grid;">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    </p>
                {% endfor %}
            </div>
            <div style="display: grid">
                <input type="submit" value="Create book"
                       class="p-4 fw-bold text-light border border-0 rounded-2 bg-black shadow">
            </div>
        </form>
    </div>
{% endblock %}

templates/article_list.html
{% extends 'base.html' %}

{% load markdown_extras %}

{% block title %}All articles{% endblock %}

{% block content %}
    <h1 class="w-50 mx-auto py-5 h1 d-flex justify-content-center">Articles</h1>
    {% for article in article_list %}
        <div class="container-fluid w-50 p-5">
            <h2>{{ article.title }}</h2>
            <img src="{{ article.image_url }}" alt="{{ article.categories }}"
                 class="img-fluid rounded mx-auto my-5 d-block">
            <p>{{ article.synopsis | safe }}</p>
            <a href="/article/{{ article.pk }}" class="btn btn-dark my-4 p-3 shadow">Start reading</a>
            <hr>
        </div>
    {% endfor %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'article/assets/blog_logo_white.svg' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <title>
        {% block title %}Tech Blog{% endblock %}
    </title>
</head>
<body style="min-height: 100vh;">
<header style="height: 10vh;">
    <nav style="height: 10vh; padding: 0 4rem" class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'article:home' %}"><img src="{% static 'article/assets/blog_logo.svg' %}" alt="Blog Logo" style="height: 40px"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="w-100 d-flex justify-content-between collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'article:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:all_articles' %}">Articles</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'article:article_create' %}">Create</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}?next={{ request.path }}"
                       class="px-4 py-3 text-light  fw-bold text-decoration-none rounded-2 bg-danger shadow">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}"
                       class="px-4 py-3 text-light  fw-bold text-decoration-none rounded-2 bg-black shadow">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
<main style="min-height: 80vh; flex: 1;">
    {% block content %}{% endblock %}
</main>
<footer style="height: 10vh; margin-top: auto;"
        class="d-flex justify-content-center align-items-center text-center text-light bg-black">
    <p class="fst-italic">Copyright(c) / F4LC0NN - 2023 / All Rights Reserved</p>
</footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid w-50 p-5">
        <div class="container-fluid mb-5 p-5 d-grid gap-3 border border-2 border-dark-subtle rounded shadow">
            <img src="{{ last_article.image_url }}" alt="{{ last_article.categories }}" class="mb-5 img-fluid rounded">
            <h1>{{ last_article.title }}</h1>
            <p>{{ last_article.synopsis }}</p>
            <a href="/article/{{ last_article.pk }}"
               class="p-3 border-0 border-dark rounded text-light text-decoration-none bg-black">I want to read!</a>
        </div>
        {% for latest_article in latest_articles %}
            <div class="w-100 mb-5">
                <h2>{{ latest_article.title }}</h2>
                <p class="mb-5">{{ latest_article.synopsis }}</p>
                <a href="/article/{{ latest_article.pk }}"
                   class="p-3 border-0 border-dark rounded text-light text-decoration-none bg-black shadow">Read
                    article</a>
            </div>
            <hr class="pb-5">
        {% endfor %}
    </div>
{% endblock %}